# Generated by Django 4.0.3 on 2022-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_id_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=1000000, primary_key=True, serialize=False),
        ),
    ]
