# Generated by Django 4.0.3 on 2022-04-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0004_remove_location_id_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(max_length=100)),
                ('receiver', models.TextField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
