# Generated by Django 4.0.3 on 2022-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0005_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='receiver',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='friend',
            name='sender',
            field=models.TextField(max_length=20),
        ),
    ]
